### ISSUE TITLE
svmtrain_lbp.py: error: unrecognized arguments: -n

### ISSUE THREAD

**Issue by 183amir** [bioidiap/antispoofing.lbp#6]
In the readme: https://github.com/bioidiap/antispoofing.lbp/blob/master/README.rst#reproduce-paper-results `-n` option is used for `svmtrain_lbp.py` but this is an unrecognizable option.

**Comment by ivana7c** [comment]
Instead of -n, the option should be --sn.

**Comment by 183amir** [comment]
Thank you very much. I will fix it.
